### ISSUE TITLE
Peer review of hw06 for shreeramsenthi

### ISSUE THREAD

**Issue by rgryba** [STAT545-UBC-students/hw06-shreeramsenthi#1]
Hi!

K - totally think that even though you did 'only' one of the questions it is super well done and thorough and my vote would be to count it as more than enough. Better to do something that you can use!

I liked the coding, nice style and clean. Nice function to check if your libraries are installed too! I never do this and it's a great idea.

My suggestions are actually more 'statsy' in nature and it's very possible would be addressed in your real data and when you do your full analysis. 
1. using an ANOVA to compare non-nested models is in most cases not the approach you want to take (AIC all the way - which you totally did - or AICc is even better)
2. Prior to plotting the models I would have probably plotted the residuals first. 
3. On your plot I would suggest not using the exponential notation (on the x-axis) and make it a bit easier for your audience to read. 

Again - nice job and the above are really just food for thought :)

**Comment by shreeramsenthi** [comment]
Thanks for kind feedback! And especially for the stats advice. I am not as comfortable with my stats as I should be, so feedback is always appreciated! 

If you don't mind my asking, is using ANOVAs for non-nested models totally wrong or just less useful than levels of support with AIC/AICc? And plotting the residuals is a way better idea than plotting the model fits! I can't believe I totally blanked on that. Thanks!

**Comment by rgryba** [comment]
Hi! Glad the stats feedback was ok - I wasn't totally sure but thought I would throwit in since your code was so bloody nice and I didn't have much to offer on that end :)

I haven't ever used ANOVAs to compare non-nested models and I do believe that it isn't the way to go. It's totally possible there are some scenarios that I'm not familiar with (I'm not a statistician) but in my experience AIC/AICc is the way to go.

**Comment by shreeramsenthi** [comment]
Sounds good! Thanks for the all the advice!
