### ISSUE TITLE
Peer review hw06

### ISSUE THREAD

**Issue by emreerhan** [STAT545-UBC-students/hw06-shreeramsenthi#2]
Peer Review 6 
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

* Excellent job on this assignment.
* You were very creative and figured out a way to complete both the functions exercise and the purr exercise in one go.
* Your coding style is almost flawless.
* Your tables were nicely formatted with kable, and your one plot was properly labelled and presented.
* Keep up the good work!

**Comment by shreeramsenthi** [comment]
Hey Emre, thanks for the kind feedback! 

Cheers,
Shree
