### ISSUE TITLE
Missing TA Feedback

### ISSUE THREAD

**Issue by shreeramsenthi** [STAT545-UBC-students/hw06-shreeramsenthi#3]
Hey @ChadFibke,

Sorry to bother you, but I never got TA feedback for this assignment and I did a fair bit worse than I expected. I was wondering if you might know who I should ask for some more comments so I know what to improve upon next time.

Thanks in advance, and sorry for the trouble!
Shree

**Comment by Rashedul** [comment]
Its me. Just updated!

**Comment by shreeramsenthi** [comment]
Perfect, thanks Rashedul!
